<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>it.enginious</groupId>
  <artifactId>fjwt</artifactId>
  <version>4.1.0</version>
  <name>fjwt</name>
  <description>fast and simple JWT authentication library</description>
  <url>https://github.com/enginious-dev/fjwt</url>
  <developers>
    <developer>
      <name>Giuseppe Milazzo</name>
      <email>giuseppe.milazzo@enginious.it</email>
      <organization>enginious</organization>
      <organizationUrl>https://www.enginious.it</organizationUrl>
    </developer>
  </developers>
  <scm>
    <url>https://github.com/enginious-dev/fjwt.git</url>
  </scm>
  <properties>
    <java.release>25</java.release>
    <importOrder>./importOrder.txt</importOrder>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <org.projectlombok.lombok.version>1.18.46</org.projectlombok.lombok.version>
    <io.jsonwebtoken.jjwt.version>0.12.6</io.jsonwebtoken.jjwt.version>
    <commons-io.commons-io.version>2.17.0</commons-io.commons-io.version>
    <org.mockito.mockito-inline.version>5.2.0</org.mockito.mockito-inline.version>
    <io.github.hakky54.logcaptor.version>2.9.3</io.github.hakky54.logcaptor.version>
    <org.jacoco.jacoco-maven-plugin.version>0.8.12</org.jacoco.jacoco-maven-plugin.version>
    <org.apache.maven.plugins.maven-compiler-plugin.version>3.11.0</org.apache.maven.plugins.maven-compiler-plugin.version>
    <org.projectlombok.lombok-maven-plugin.version>1.18.20.0</org.projectlombok.lombok-maven-plugin.version>
    <org.apache.maven.plugins.maven-antrun-plugin.version>3.1.0</org.apache.maven.plugins.maven-antrun-plugin.version>
    <org.codehaus.mojo.build-helper-maven-plugin.version>3.6.0</org.codehaus.mojo.build-helper-maven-plugin.version>
    <org.apache.maven.plugins.maven-javadoc-plugin.version>3.10.1</org.apache.maven.plugins.maven-javadoc-plugin.version>
    <org.apache.maven.plugins.maven-surefire-plugin.version>3.5.1</org.apache.maven.plugins.maven-surefire-plugin.version>
    <com.diffplug.spotless.spotless-maven-plugin.version>3.8.0</com.diffplug.spotless.spotless-maven-plugin.version>
    <com.google.googlejavaformat.google-java-format.version>1.35.0</com.google.googlejavaformat.google-java-format.version>
  </properties>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-dependencies</artifactId>
        <version>4.1.0</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <dependencies>
    <!-- spring -->
    <!-- https://mvnrepository.com/artifact/org.springframework.boot/spring-boot -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-configuration-processor -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-configuration-processor</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-security -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-security</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-data-ldap -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-ldap</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- https://mvnrepository.com/artifact/org.springframework.security/spring-security-ldap -->
    <dependency>
      <groupId>org.springframework.security</groupId>
      <artifactId>spring-security-ldap</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-validation -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-validation</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- other -->
    <!-- https://mvnrepository.com/artifact/io.jsonwebtoken/jjwt-api -->
    <dependency>
      <groupId>io.jsonwebtoken</groupId>
      <artifactId>jjwt-api</artifactId>
      <version>${io.jsonwebtoken.jjwt.version}</version>
    </dependency>
    <!-- https://mvnrepository.com/artifact/io.jsonwebtoken/jjwt-impl -->
    <dependency>
      <groupId>io.jsonwebtoken</groupId>
      <artifactId>jjwt-impl</artifactId>
      <version>${io.jsonwebtoken.jjwt.version}</version>
    </dependency>
    <!-- https://mvnrepository.com/artifact/io.jsonwebtoken/jjwt-jackson -->
    <dependency>
      <groupId>io.jsonwebtoken</groupId>
      <artifactId>jjwt-jackson</artifactId>
      <version>${io.jsonwebtoken.jjwt.version}</version>
    </dependency>
    <!-- https://mvnrepository.com/artifact/org.projectlombok/lombok -->
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- https://mvnrepository.com/artifact/jakarta.servlet/jakarta.servlet-api -->
    <dependency>
      <groupId>jakarta.servlet</groupId>
      <artifactId>jakarta.servlet-api</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- https://mvnrepository.com/artifact/org.apache.commons/commons-lang3 -->
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-lang3</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- https://mvnrepository.com/artifact/commons-io/commons-io -->
    <dependency>
      <groupId>commons-io</groupId>
      <artifactId>commons-io</artifactId>
      <version>${commons-io.commons-io.version}</version>
      <scope>provided</scope>
    </dependency>
    <!-- test -->
    <!-- https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-web -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
      <scope>test</scope>
    </dependency>
    <!-- https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-test -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <scope>test</scope>
    </dependency>
    <!-- Source: https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-webmvc-test -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-webmvc-test</artifactId>
      <scope>test</scope>
    </dependency>
    <!-- https://mvnrepository.com/artifact/io.github.hakky54/logcaptor -->
    <dependency>
      <groupId>io.github.hakky54</groupId>
      <artifactId>logcaptor</artifactId>
      <version>${io.github.hakky54.logcaptor.version}</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <!-- https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-compiler-plugin -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>${org.apache.maven.plugins.maven-compiler-plugin.version}</version>
        <configuration>
          <release>${java.release}</release>
          <debug>true</debug>
          <debuglevel>lines,vars,source</debuglevel>
        </configuration>
        <executions>
          <execution>
            <id>default-compile</id>
            <configuration>
              <compileSourceRoots>
                <compileSourceRoot>${project.build.directory}/delombok</compileSourceRoot>
              </compileSourceRoots>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <!-- https://mvnrepository.com/artifact/org.projectlombok/lombok-maven-plugin -->
      <plugin>
        <groupId>org.projectlombok</groupId>
        <artifactId>lombok-maven-plugin</artifactId>
        <version>${org.projectlombok.lombok-maven-plugin.version}</version>
        <dependencies>
          <!-- https://mvnrepository.com/artifact/org.projectlombok/lombok -->
          <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${org.projectlombok.lombok.version}</version>
          </dependency>
        </dependencies>
        <executions>
          <execution>
            <id>delombok-sources</id>
            <goals>
              <goal>delombok</goal>
            </goals>
            <phase>generate-sources</phase>
            <configuration>
              <sourceDirectory>src/main/java</sourceDirectory>
              <outputDirectory>${project.build.directory}/delombok</outputDirectory>
              <addOutputDirectory>false</addOutputDirectory>
              <encoding>UTF-8</encoding>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <!-- https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-antrun-plugin -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-antrun-plugin</artifactId>
        <version>${org.apache.maven.plugins.maven-antrun-plugin.version}</version>
        <executions>
          <execution>
            <id>generate-delomboked-sources-jar</id>
            <goals>
              <goal>run</goal>
            </goals>
            <phase>package</phase>
            <configuration>
              <target>
                <jar basedir="${project.build.directory}/delombok" destfile="${project.build.directory}/${project.build.finalName}-sources.jar"/>
              </target>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <!-- https://mvnrepository.com/artifact/org.codehaus.mojo/build-helper-maven-plugin -->
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>build-helper-maven-plugin</artifactId>
        <version>${org.codehaus.mojo.build-helper-maven-plugin.version}</version>
        <executions>
          <execution>
            <id>attach-delomboked-sources-jar</id>
            <goals>
              <goal>attach-artifact</goal>
            </goals>
            <phase>package</phase>
            <configuration>
              <artifacts>
                <artifact>
                  <file>${project.build.directory}/${project.build.finalName}-sources.jar</file>
                  <type>jar</type>
                  <classifier>sources</classifier>
                </artifact>
              </artifacts>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <!-- https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-javadoc-plugin -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-javadoc-plugin</artifactId>
        <version>${org.apache.maven.plugins.maven-javadoc-plugin.version}</version>
        <executions>
          <execution>
            <id>attach-javadocs</id>
            <goals>
              <goal>jar</goal>
            </goals>
            <phase>package</phase>
            <configuration>
              <sourcepath>${project.build.directory}/delombok</sourcepath>
              <encoding>UTF-8</encoding>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <!-- https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-surefire-plugin -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>${org.apache.maven.plugins.maven-surefire-plugin.version}</version>
      </plugin>
    </plugins>
  </build>
  <profiles>
    <profile>
      <id>sonar</id>
      <properties>
        <sonar.java.coveragePlugin>jacoco</sonar.java.coveragePlugin>
        <sonar.dynamicAnalysis>reuseReports</sonar.dynamicAnalysis>
        <sonar.coverage.jacoco.xmlReportPaths>${project.basedir}/../target/jacoco.xml</sonar.coverage.jacoco.xmlReportPaths>
        <sonar.language>java</sonar.language>
      </properties>
      <dependencies>
        <!-- https://mvnrepository.com/artifact/org.jacoco/jacoco-maven-plugin -->
        <dependency>
          <groupId>org.jacoco</groupId>
          <artifactId>jacoco-maven-plugin</artifactId>
          <version>${org.jacoco.jacoco-maven-plugin.version}</version>
        </dependency>
      </dependencies>
      <build>
        <plugins>
          <!-- https://mvnrepository.com/artifact/org.jacoco/jacoco-maven-plugin -->
          <plugin>
            <groupId>org.jacoco</groupId>
            <artifactId>jacoco-maven-plugin</artifactId>
            <version>${org.jacoco.jacoco-maven-plugin.version}</version>
            <executions>
              <execution>
                <id>jacoco-initialize</id>
                <goals>
                  <goal>prepare-agent</goal>
                </goals>
              </execution>
              <execution>
                <id>jacoco-site</id>
                <goals>
                  <goal>report</goal>
                </goals>
                <phase>package</phase>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>
    <profile>
      <id>spotless</id>
      <activation>
        <file>
          <exists>${importOrder}</exists>
        </file>
      </activation>
      <build>
        <plugins>
          <plugin>
            <groupId>com.diffplug.spotless</groupId>
            <artifactId>spotless-maven-plugin</artifactId>
            <version>${com.diffplug.spotless.spotless-maven-plugin.version}</version>
            <configuration>
              <java>
                <googleJavaFormat>
                  <version>${com.google.googlejavaformat.google-java-format.version}</version>
                  <style>GOOGLE</style>
                  <formatJavadoc>true</formatJavadoc>
                  <reorderImports>false</reorderImports>
                </googleJavaFormat>
                <formatAnnotations/>
                <importOrder>
                  <file>${importOrder}</file>
                  <semanticSort>true</semanticSort>
                </importOrder>
              </java>
              <pom>
                <includes>
                  <include>**/pom.xml</include>
                </includes>
                <excludes>
                  <exclude>**/target/**</exclude>
                </excludes>
                <sortPom>
                  <expandEmptyElements>false</expandEmptyElements>
                  <spaceBeforeCloseEmptyElement>false</spaceBeforeCloseEmptyElement>
                  <keepBlankLines>false</keepBlankLines>
                  <nrOfIndentSpace>2</nrOfIndentSpace>
                  <indentAttribute>schemaLocation</indentAttribute>
                  <predefinedSortOrder>recommended_2008_06</predefinedSortOrder>
                </sortPom>
              </pom>
            </configuration>
            <executions>
              <execution>
                <id>spotless-validation</id>
                <goals>
                  <goal>check</goal>
                </goals>
                <phase>validate</phase>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>
</project>
